import Head from 'next/head'
import Image from 'next/image'
import { GetStaticProps } from 'next'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import prisma from '../../lib/prisma'
import { Todo } from '@prisma/client'
import { useReducer } from 'react'
// import { reducer, makeDispatch, State, Action, Reducer } from '../../lib/state'
import { reducer, State, actionMapping } from '../../lib/state-async'
import { makeAsyncStore, ActionMapping, Reducer } from "../../lib/state-lib"

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps: GetStaticProps = async () => {
  const todos: Todo[] = []; // await prisma.todo.findMany();

  return {
    props: { todos },
    revalidate: 10,
  };
};

type Props = {
  todos: Todo[],
}

function useAsyncReducer<State, Action>(actionMapping: ActionMapping<State, Action>, reducer: Reducer<State, Action>, init: State) {
  const [state, dispatch] = useReducer(reducer, init);
  const getState = () => state;
  
  const store = {
    dispatch: dispatch,
    getState,
  }
    
  return makeAsyncStore(actionMapping, state, store);
}

export default function Home({ todos }: Props) {
  const [state, dispatch] = useAsyncReducer(actionMapping, reducer, { isLoading: false, todos });

  const addTodo = () => {
    dispatch({ type: "create_todo", todo: { name: "T1", isComplete: false } });
  }

  return (
    <>
      <Head>
        <title>Todo Sligh App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Todos</p>
        {todos.map(t => t.name)}
        {state.todos.map(t => t.name)}
        <button onClick={addTodo}>Add Todo</button>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
